### ISSUE TITLE
Мердж списков в манифесте

### ISSUE THREAD

**Issue by kulikov** [InnovaCo/serve#58]
```
build:
  - debian:
      deploy-path: "/local/innova/tools"
```

и

```
build:
  - debian: 
      daemon: "$APPLICATION_PATH/bin/start"
```

в итоге должны давать:
```
build:
  - debian: 
      daemon: "$APPLICATION_PATH/bin/start"
      deploy-path: "/local/innova/tools"
```
